const express = require('express');
const router  = express.Router();
const canchaController = require('../controllers/canchaController');
const verifyToken = require('../middleware/verifyToken');
const checkRole   = require('../middleware/checkRole');
router.get('/',                    canchaController.getAllPublic.bind(canchaController));
router.get('/admin/list', verifyToken, checkRole('admin'), canchaController.getAllAdmin.bind(canchaController));
router.get('/:id/disponibilidad',  canchaController.getDisponibilidad.bind(canchaController));
router.get('/:id',                 canchaController.getById.bind(canchaController));
router.post('/',   verifyToken, checkRole('admin'), canchaController.create.bind(canchaController));
router.put('/:id', verifyToken, checkRole('admin'), canchaController.update.bind(canchaController));
module.exports = router;
